/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#131313",
        "surface-dim": "#131313",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#353534",
        "on-surface": "#e5e2e1",
        "on-surface-variant": "#b9cacb",
        "inverse-surface": "#e5e2e1",
        "inverse-on-surface": "#313030",
        outline: "#849495",
        "outline-variant": "#3b494b",
        "surface-tint": "#00dbe9",
        primary: "#dbfcff",
        "on-primary": "#00363a",
        "primary-container": "#00f0ff",
        "on-primary-container": "#006970",
        "inverse-primary": "#006970",
        secondary: "#d7ffc5",
        "on-secondary": "#053900",
        "secondary-container": "#2ff801",
        "on-secondary-container": "#0f6d00",
        tertiary: "#faf3ff",
        "on-tertiary": "#3c0090",
        "tertiary-container": "#e1d2ff",
        "on-tertiary-container": "#7213ff",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#7df4ff",
        "primary-fixed-dim": "#00dbe9",
        "on-primary-fixed": "#002022",
        "on-primary-fixed-variant": "#004f54",
        "secondary-fixed": "#79ff5b",
        "secondary-fixed-dim": "#2ae500",
        "on-secondary-fixed": "#022100",
        "on-secondary-fixed-variant": "#095300",
        "tertiary-fixed": "#e9ddff",
        "tertiary-fixed-dim": "#d1bcff",
        "on-tertiary-fixed": "#23005b",
        "on-tertiary-fixed-variant": "#5700c9",
        background: "#131313",
        "on-background": "#e5e2e1",
        "surface-variant": "#353534",
      },
      borderRadius: {
        sm: "0.125rem",
        DEFAULT: "0.25rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1280px",
        gutter: "24px",
        "margin-mobile": "16px",
        "unit-xs": "4px",
        "unit-sm": "8px",
        "unit-md": "16px",
        "unit-lg": "32px",
        "unit-xl": "64px",
      },
      fontFamily: {
        "headline-xl": ['"Space Grotesk"', "sans-serif"],
        "headline-lg": ['"Space Grotesk"', "sans-serif"],
        "headline-md": ['"Space Grotesk"', "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "code-sm": ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
      },
      fontSize: {
        "headline-xl": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" },
        ],
      },
    },
  },
  plugins: [],
};
